name: Build Docker Image Lilypond Action
on:
  push:
    tags:
      - 'v*'

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get the version
        id: get_version
        run: |
          echo ::set-output name=GHCR_TAG::ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF/refs\/tags\//}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.get_version.outputs.GHCR_TAG }}

